apiVersion: apps/v1
kind: Deployment
metadata:
  name: consommi_tounsi
  labels:
    app: consommi_tounsi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consommi_tounsi
  template:
    metadata:
      labels:
        app: consommi_tounsi
    spec:
      containers:
      - name: consommi_tounsi
        image: nawressbr/consommi-front
        ports:
        - containerPort: 80
       
---
apiVersion: v1
kind: Service
metadata:
  name: consommisvc
spec:
  selector:
    app: consommi_tounsi
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30000
